Code refactoring

diff --git a/email/patchman-email b/email/patchman-email
--- a/email/patchman-email
+++ b/email/patchman-email
@@ -16,7 +16,7 @@ getConfig() {
 }
 
 getPackages() {
-    echo "$(MYSQL_PWD=$PASSWORD mysql -u $USERNAME $DATABASE -Nrse \
+    MYSQL_PWD="$PASSWORD" mysql -u "$USERNAME" "$DATABASE" -Nrse \
         "SELECT \`update\`
         FROM hosts_host
         LEFT JOIN (
@@ -41,20 +41,20 @@ getPackages() {
                 ) AS newpackage ON packages_packageupdate.newpackage_id=newpackage.id
             ) AS package ON hosts_host_updates.packageupdate_id=package.id
         ) AS updates ON hosts_host.id=updates.host_id
-        WHERE hosts_host.reversedns=\"$1\";")"
+        WHERE hosts_host.reversedns=\"$1\";"
 }
 
 email() {
     SENDER=$(getConfig General sender)
 
-    if [ ! -z $SENDER ]; then
-        RECIPIENT=$(getConfig $1 recipient)
+    if [ -n "$SENDER" ]; then
+        RECIPIENT=$(getConfig "$1" recipient)
     
-        if [ ! -z $RECIPIENT ]; then
+        if [ -n "$RECIPIENT" ]; then
             ATTACHMENTS=()
             BOUNDARY=$(uuidgen)
-            CC=$(getConfig $1 cc)
-            BCC=$(getConfig $1 bcc)
+            CC=$(getConfig "$1" cc)
+            BCC=$(getConfig "$1" bcc)
             FULLNAME=$(getConfig General fullname)
             SUBJECT=$(echo "[$1] $(getConfig General subject)" | base64)
             BODY="<html><style>
@@ -76,10 +76,10 @@ email() {
                 Remember your Environmental Responsibility before deciding to print this email.
                 </div></body></html>"
             
-            if [ -z $2 ]; then
-                ATTACHMENTS+=$(ls $DIR/$1/*-$DATE.html)
+            if [ -z "$2" ]; then
+                mapfile -t ATTACHMENTS < <(ls "$DIR"/"$1"/*-"$DATE".html)
             else
-                ATTACHMENTS+=$(ls $DIR/$1/$2-$DATE.html)
+                mapfile -t ATTACHMENTS < <(ls "$DIR"/"$1"/"$2"-"$DATE".html)
             fi
             
             echo "$(date '+%d/%m/%Y %R') [INFO] $1: E-mailing report..."
@@ -95,18 +95,18 @@ email() {
             echo "Content-Type: text/html; charset=UTF-8"
             echo "Content-Disposition: inline"
             echo ""
-            echo $BODY
-            for ATTACH in $ATTACHMENTS; do
+            echo "$BODY"
+            for ATTACH in "${ATTACHMENTS[@]}"; do
                 echo ""
                 echo "--$BOUNDARY"
                 echo "Content-Type: text/html;"
                 echo "Content-Transfer-Encoding: uuencode"
-                echo "Content-Disposition: attachment; filename=\"$(basename $ATTACH)\""
+                echo "Content-Disposition: attachment; filename=\"$(basename "$ATTACH")\""
                 echo ""
-                uuencode $ATTACH $(basename $ATTACH)
+                uuencode "$ATTACH" "$(basename "$ATTACH")"
             done
             echo "--$BOUNDARY--"
-            ) | /usr/sbin/sendmail -t -f $SENDER -F "$FULLNAME"
+            ) | /usr/sbin/sendmail -t -f "$SENDER" -F "$FULLNAME"
             
             if [ $? -eq 0 ]; then
                 echo "$(date '+%d/%m/%Y %R') [SUCCESS] $1: E-mail report sent."
@@ -123,43 +123,45 @@ email() {
 
 report() {
     # Gets host info
-    HOST=$(patchman -lh -H $1 | tail -n +3 | head -n -1 | sed 's/\x1b\[[0-9;]*m//g')
+    HOST=$(patchman -lh -H "$1" | tail -n +3 | head -n -1 | sed 's/\x1b\[[0-9;]*m//g')
     
     # Gets the number of updates available for the host
     UPDATES=$(echo "$HOST" | awk -F ' : ' 'NR==10 { print $2 }')
     
-    if [ -z $UPDATES ]; then
+    if [ -z "$UPDATES" ]; then
         echo "$(date '+%d/%m/%Y %R') [ERROR] $1: Hostname not found."
-    elif [ $UPDATES -gt 0 ]; then
+    elif [ "$UPDATES" -gt 0 ]; then
         # Gets the hosts tags to determine the recipient and directory
         TAG=$(echo "$HOST" | awk -F ' : ' 'NR==11 { print $2 }')
         
         # Creates the directory where the e-mail file will be stored, if it doesnt exist
         FILE=$DIR/$TAG/$1-$DATE.html
-        mkdir -p $(echo $FILE | sed 's|\(.*\)/.*|\1|')
+        mkdir -p "$DIR"/"$TAG"
         
         # Queries the database for available package updates
-        QUERY=$(getPackages $1)
+        QUERY=$(getPackages "$1")
         
         # Creates the report if it doesnt exist
-        if [ ! -f $FILE ]; then
+        if [ ! -f "$FILE" ]; then
             echo "$(date '+%d/%m/%Y %R') [INFO] $TAG $1: Creating report..."
             
-            echo "<html><style>" > $FILE
-            echo "body { font-family: \"Calibri\"  }" >> $FILE
-            echo "#details table { border-collapse: collapse; width: 20em; white-space: nowrap;}" >> $FILE
-            echo "#updates table { border-collapse: collapse; width: 100%; }" >> $FILE
-            echo "#details th, #details tr, #details td { text-align: left; }" >> $FILE
-            echo "#updates th, #updates td { padding: 8px; text-align: left; border-bottom: 1px solid #ddd; }" >> $FILE
-            echo "</style><head><meta charset=\"UTF-8\"></head><body>" >> $FILE
-            echo "<div id=\"details\"><table>" >> $FILE
-            echo "$HOST" | awk -F ' : ' 'NR!=7 && NR!=9 && NR!=11 && NR!=12 && NR!=13 && NR!=14 { print "<tr><th>"$1"</th><th>:&nbsp;</th><td>"$2"</td></tr>" }' | sed 's/Reverse DNS/Hostname/g' >> $FILE
-            echo "</table></div><br>" >> $FILE
-            echo "<div id=\"updates\"><table>" >> $FILE
-            echo "<tr><th>Current Version</th><th>New Version</th><th>Type</th></tr>" >> $FILE
-            echo "$QUERY" | sort -n | uniq | sed 's/[()]//g' | awk '{ print "<tr><td>"$1"</td><td>"$3"</td><td>"$4"</td></tr>" }' >> $FILE
-            echo "</table></div><br>" >> $FILE
-            echo "</body></html>" >> $FILE
+            cat <<-EOF > "$FILE"
+				<html><style>
+				body { font-family: "Calibri" }
+				#details table { border-collapse: collapse; width: 20em; white-space: nowrap;}
+				#updates table { border-collapse: collapse; width: 100%; }
+				#details th, #details tr, #details td { text-align: left; }
+				#updates th, #updates td { padding: 8px; text-align: left; border-bottom: 1px solid #ddd; }
+				</style><head><meta charset="UTF-8"></head><body>
+				<div id="details"><table>
+				$(echo "$HOST" | awk -F ' : ' 'NR!=7 && NR!=9 && NR!=11 && NR!=12 && NR!=13 && NR!=14 { print "<tr><th>"$1"</th><th>:&nbsp;</th><td>"$2"</td></tr>" }' | sed 's/Reverse DNS/Hostname/g')
+				</table></div><br>
+				<div id=\"updates\"><table>
+				<tr><th>Current Version</th><th>New Version</th><th>Type</th></tr>
+				$(echo "$QUERY" | sort -n | uniq | sed 's/[()]//g' | awk '{ print "<tr><td>"$1"</td><td>"$3"</td><td>"$4"</td></tr>" }')
+				</table></div><br>
+				</body></html>
+			EOF
         else
             echo "$(date '+%d/%m/%Y %R') [INFO] $TAG $1: Report exists, skipping."
         fi
@@ -188,17 +190,17 @@ if [ $# -gt 0 ] && [[ $1 == -* ]]; then
                     DATE=$(date +%Y%m%d)
                     HOSTS=()
                     TAGS=()
-                    HOSTS+=$(patchman -lh | tail -n +3 | awk -F ' : ' 'NR%16==3 { print $2 }' | sed 's/\x1b\[[0-9;]*m//g')
-                    TAGS=$(patchman -lh | tail -n +3 | awk -F ' : ' 'NR%16==12 { print $2 }' | sort -n | uniq | sed 's/\x1b\[[0-9;]*m//g')
+                    mapfile -t HOSTS < <(patchman -lh | tail -n +3 | awk -F ' : ' 'NR%16==3 { print $2 }' | sed 's/\x1b\[[0-9;]*m//g')
+                    mapfile -t TAGS < <(patchman -lh | tail -n +3 | awk -F ' : ' 'NR%16==12 { print $2 }' | sort -n | uniq | sed 's/\x1b\[[0-9;]*m//g')
                     
                     # Generate report
-                    for HOST in $HOSTS; do
-                        report $HOST
+                    for HOST in "${HOSTS[@]}"; do
+                        report "$HOST"
                     done
                     
                     # E-mails the report
-                    for TAG in $TAGS; do
-                        email $TAG
+                    for TAG in "${TAGS[@]}"; do
+                        email "$TAG"
                     done
                 fi
                 ;;
@@ -209,11 +211,10 @@ if [ $# -gt 0 ] && [[ $1 == -* ]]; then
                 else
                     DIR=$(getConfig General dir)
                     DATE=$(date +%Y%m%d)
-                    HOSTS=${OPTARG}
+                    HOST=${OPTARG}
                     
-                    report $HOSTS
-                    
-                    email $TAG $HOSTS
+                    report "$HOST"
+                    email "$TAG" "$HOST"
                 fi
                 ;;
             T)
@@ -224,17 +225,17 @@ if [ $# -gt 0 ] && [[ $1 == -* ]]; then
                     DIR=$(getConfig General dir)
                     DATE=$(date +%Y%m%d)
                     HOSTS=()
-                    HOSTS+=$(patchman -lh | tail -n +3 | awk -F ' : ' 'NR%16==3 || NR%16==12 {print $2}' | paste -d : - - | awk -F ':' '{ if( $2 == "'${OPTARG}'" ){ print $1 }}' | sed 's/\x1b\[[0-9;]*m//g')
+                    mapfile -t HOSTS < <(patchman -lh | tail -n +3 | awk -F ' : ' 'NR%16==3 || NR%16==12 {print $2}' | paste -d : - - | awk -F ':' '{ if( $2 == "'"${OPTARG}"'" ){ print $1 }}' | sed 's/\x1b\[[0-9;]*m//g')
                     
-                    if [ -z "$HOSTS" ]; then
-                        echo "$(date '+%d/%m/%Y %R') [ERROR] ${OPTARG}: Tag not found."
-                        exit 1
-                    else
-                        for HOST in $HOSTS; do
-                            report $HOST
+                    if [ "${#HOSTS[@]}" -gt 0 ]; then
+                        for HOST in "${HOSTS[@]}"; do
+                            report "$HOST"
                         done
                         
-                        email $TAG
+                        email "$TAG"
+                    else
+                        echo "$(date '+%d/%m/%Y %R') [ERROR] ${OPTARG}: Tag not found."
+                        exit 1
                     fi
                 fi
                 ;;
